[package]
name = "blis"
version = "4.0.0"
edition = "2021"

[dependencies]
create_process_w = { version = "0.1.3", package = "CreateProcessW" }
gtk = { version = "0.8.0", package = "gtk4", features = ["v4_12"] }
handlebars = "4.5.0"
webbrowser = "0.8.13"
