[package]
name = "blis"
version = "4.0.0"
edition = "2021"

[dependencies]
native-windows-gui = "1.0.12"
native-windows-derive = "1.0.3"
create_process_w = { version = "0.1.3", package = "CreateProcessW" }
