[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--target=x86_64-pc-windows-gnu"]
dependencies = ["clean"]

[tasks.run]
command = "wine"
args = ["target/x86_64-pc-windows-gnu/debug/blis.exe"]
dependencies = ["build"]
